kubeedge/sedna

hack/local-up.sh
this could avoid our images be removed which leads to local-up script
failure since edgecore image gc would be triggered when high image
usage(>=80%).
=> local-up.sh: start kubeedge before building images

docs/setup/install.md, scripts/installation/install.sh
=> Add all-in-one installation script

pkg/globalmanager/common.go, pkg/globalmanager/federatedlearningjob.go, pkg/globalmanager/jointinferenceservice.go, pkg/globalmanager/worker.go
When a jointinferenceservice is created, a k8s service is created for
big worker, so the big-worker's lables need to be unique.
This can be done by adding a new label key 'worker-type'.
Same as federatedlearningjob.
=> Fix k8s-service selector issue

pkg/globalmanager/storage_initializer_injector.go
Fix the case user creates a dataset/model CR with url like '/model.pb',
in present GM will attach its parent directory '/' into the worker,
the volume name generated from '/' will be empty.
=> Fall back to default volume when mounting '/'

Makefile
Currently, the sedna-kb image cannot be compiled using the command `make images` . This patch fixes this problem
=> Fix the problem that kbimage cannot be compiled in Makefile

examples/joint_inference/helmet_detection_inference/big_model/big_model.py, examples/joint_inference/helmet_detection_inference/big_model/interface.py, examples/joint_inference/helmet_detection_inference/little_model/interface.py, examples/joint_inference/helmet_detection_inference/little_model/little_model.py, lib/sedna/common/config.py, lib/sedna/core/joint_inference/joint_inference.py, lib/sedna/service/client.py
1. fix example bug: save result which get from cloud if is hard example
2. Add docs and code comment
3. rename: TSBigModelService -> BigModelService
4. fix #133
=> joint_inference: bug fix and interface reconstruction

.github/workflows/image-publish.yaml
fix #90 
This commit creates a github action which does the following steps:
1. login docker hub.
2. checkout the project, and run `make push-all`.
And when we create a new release this action will be triggered to run.
Tested in my personal fork, see https://github.com/llhuii/sedna/actions/runs/1126507005.
=> Push images automatically when a new release is created

pkg/localcontroller/db/db.go, pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
**What this PR does / why we need it:**
When these are situations，such as the node being restarted，the LC will be restarted, then LC should recover incremental learning job.
**Which issue(s) this PR fixes:**
fix issue: https://github.com/kubeedge/sedna/issues/140
=> IL: LC supports to recover job when restart

.github/workflows/image-publish.yaml
From https://github.com/kubeedge/sedna/actions/runs/1134112088, GITHUB_ACTOR is the github user who has created the release, this is unexpected for the right image repo name `kubeedge`.
So using the env 'GITHUB_REPOSITORY' whose value is `kubeedge/sedna`.
=> Fix IMAGE_REPO in github image-publish action

lib/requirements.txt
- This upgrade fixes a CSRF error in FastAPI version earlier than 0.65.2,
see https://github.com/tiangolo/fastapi/security/advisories/GHSA-8h2j-cgx8-6xv7
=> fix lib/requirements

scripts/installation/install.sh
In some environment, GM will use about 150M memory.
This avoids GM to be OOM killed temporarily.
TBD: Dive to analyze GM memory usage, which should be less than 128Mi.
=> Increase GM memory limit from 128Mi to 256Mi

pkg/globalmanager/runtime/worker.go
The 'externalIPs' is unnecessary, and in some environment can result in the correspoing
kubelet can't reach api server, and then node unreachable status.
Signed-off-by: llhuii <liulinghui@huawei.com>
=> GM: remove externalIPs when creating k8s service

README.md, docs/setup/all-in-one.md, docs/setup/install.md, docs/setup/local-up.md, docs/setup/quick-start.md, scripts/installation/all-in-one.sh, scripts/installation/build-allinone-image.sh
=> Add all-in-one installation script/docs

pkg/globalmanager/controllers/objectsearch/downstream.go, pkg/globalmanager/controllers/objectsearch/objectsearchservice.go, pkg/globalmanager/controllers/objectsearch/upstream.go, pkg/globalmanager/controllers/registry.go, pkg/globalmanager/runtime/common.go, pkg/globalmanager/runtime/worker.go
- Add the object search controller to GM
The user worker and ReID workers can be created on both cloud and edge. ( EdgeMesh v1.8 supports cross edge-cloud communication.)
=> Add object search controller

.github/workflows/image-publish.yaml, .github/workflows/main.yaml, Makefile, hack/lib/buildx.sh, hack/lib/init.sh, hack/make-rules/cross-build.sh, hack/make-rules/push.sh
fix issues: https://github.com/kubeedge/sedna/issues/170
=> Sedna control plane supports amd64/arm64

scripts/installation/all-in-one.sh
If NO_INSTALL_SEDNA not 'false', don't install Sedna, it's useful to
develop, the developer will install Sedna later by manually.
Signed-off-by: llhuii <liulinghui@huawei.com>
=> all-in-one: add NO_INSTALL_SEDNA variable flag

Makefile, hack/lib/buildx.sh
=> Fix building wrong GM/LC arm64 docker images

build/crd-samples/sedna/lifelonglearningjobv1alpha1.yaml, docs/contributing/lib/datasets.md, docs/contributing/lib/development.md, docs/contributing/lib/new_algorithm.md, docs/contributing/prepare-environment.md, docs/index.rst, docs/quickstart.md, docs/related_link.md
- add lib development guide
- Supplementary quickstart documentation
- fix known issue
=> Update docs: add lib development guide

pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
=> Fix IL bug: job misses first data when reads data.

examples/build_image.sh
fix the missing `sedna-example-` prefix image name bug introduced by #214, else our push script would [report something](https://github.com/kubeedge/sedna/actions/runs/1416003481):
```
2021-11-03T10:09:09.0703862Z denied: requested access to the resource is denied
2021-11-03T10:09:09.0724598Z failed to docker push kubeedge/federated-learning-surface-defect-detection-aggregation:v0.4.3
2021-11-03T10:09:09.1243181Z The push refers to repository [docker.io/kubeedge/federated-learning-mistnet-yolo-client]
```
=> examples: fix the image name prefix

pkg/apis/sedna/v1alpha1/federatedlearningjob_types.go, pkg/apis/sedna/v1alpha1/jointinferenceservice_types.go, pkg/apis/sedna/v1alpha1/objectsearchservice_types.go, pkg/apis/sedna/v1alpha1/objecttrackingservice_types.go, pkg/apis/sedna/v1alpha1/register.go
Signed-off-by: xujingjing xujingjing_yewu@cmss.chinamobile.com
What type of PR is this?
/kind cleanup
What this PR does / why we need it:
fix grammar error in api module
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
=> fix grammar error in api module

pkg/globalmanager/config/config.go, pkg/globalmanager/controllers/federatedlearning/upstream.go, pkg/globalmanager/controllers/incrementallearning/incrementallearningjob.go, pkg/globalmanager/controllers/incrementallearning/upstream.go, pkg/globalmanager/controllers/jointinference/upstream.go, pkg/globalmanager/controllers/lifelonglearning/downstream.go, pkg/globalmanager/controllers/lifelonglearning/lifelonglearningjob.go, pkg/globalmanager/controllers/lifelonglearning/upstream.go, pkg/globalmanager/controllers/objectsearch/objectsearchservice.go
Signed-off-by: xujingjing xujingjing_yewu@cmss.chinamobile.com
What type of PR is this?
/kind cleanup
What this PR does / why we need it:
fix grammar error in globalmanager module
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
=> fix grammar error in globalmanager module

.github/workflows/main.yaml, build/gm/Dockerfile, build/lc/Dockerfile, go.mod
The CI checker [`E2e test`](https://github.com/kubeedge/sedna/runs/4453911167?check_suite_focus=true) depends the lastest kubeedge which requires golang `1.16`, here we upgrade our golang verison to `1.16`.
=> Upgrade golang from 1.14 to 1.16

lib/requirements.txt
Signed-off-by: Jie Pu <i@jaypu.com>
=> Fix the wrong uvicorn version in sedna lib

docs/setup/all-in-one.md
1.recommend to use the stable version v1.8.0 of kubeedge.
2.add clean all-in-one Sedna
=> Fix all-in-one doc

pkg/localcontroller/db/db.go
=> Fixbug: db path has missed the mount volume prefix in LC

pkg/globalmanager/controllers/incrementallearning/downstream.go
bug: after deleting dataset, the event of deleting job can be sent to LC.
=> Fix downstream bug in IL

lib/requirements.dev.txt, lib/sedna/algorithms/optical_flow/__init__.py
Signed-off-by: Vittorio Cozzolino <vittorio.cozzolino@huawei.com>
/kind bug
Move algorithm-specific dependencies into the class definition for the optical flow module. This should lift the requirement to have extra dependencies in the KB image.
Fixes #320
=> Move algorithm-specific dependencies into class definition (optical flow)

lib/sedna/algorithms/__init__.py
Signed-off-by: Jie Pu <pujie2@huawei.com>
/kind bug
Python package `cv2` should not be imported in kb image by default.
=> Fix kb not starting normally after installation

examples/lifelong_learning/RFNet/basemodel.py, examples/lifelong_learning/RFNet/dataloaders/utils.py, examples/lifelong_learning/RFNet/eval.py, examples/lifelong_learning/RFNet/predict.py, examples/lifelong_learning/RFNet/sedna_evaluate.py, examples/lifelong_learning/RFNet/sedna_predict.py, examples/lifelong_learning/RFNet/sedna_train.py, examples/lifelong_learning/RFNet/train.py, lib/sedna/algorithms/knowledge_management/edge_knowledge_management.py, lib/sedna/algorithms/seen_task_learning/seen_task_learning.py, lib/sedna/algorithms/seen_task_learning/task_allocation/task_allocation_by_origin.py, lib/sedna/algorithms/seen_task_learning/task_definition/task_definition_by_origin.py, lib/sedna/core/lifelong_learning/lifelong_learning.py, lib/sedna/datasources/__init__.py, lib/sedna/service/server/knowledgeBase/server.py
Signed-off-by: luosiqi <1587295470@qq.com>
This PR executes code cleaning, improves base model functions and fixes some bugs in lifelong learning updates.
=> Code check and base model improvement of unstructured lifelong learning framework

.github/workflows/main.yaml
Fix ci e2e running failed issue.
The github action runner image `ubuntu22.04` has upgrade kind version from v0.18.0 to v0.19.0:
https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
but this will lead  sedna `all-in-one.sh` running failed in github action, for the  incompatible interface.
=> Fix ci e2e running failed issue.

lib/requirements.txt
/kind cleanup
The latest `pip` has deprecated certain interface, making sedna's dependency `uvicorn~=0.14.0` cannot be installed.
This PR change `uvicorn`'s version from `0.14.0` to `0.15.0` to fix this problem.
Fixes #440
=> Update uvicorn's version in `lib/requirements.txt` to fix installation issue with latest `pip`
