kubeedge/sedna

- build/gm/gm-config.yaml
- docs/setup/install.md
1. add note about the node GM deployed
2. remove build sections
3. squash GM's steps
4. fix some misleading sentences
> docs: update installation instructions

- examples/federated_learning/surface_defect_detection/README.md
Signed-off-by: JimmyYang <yangjin39@huawei.com>
> Fix example of federated learning

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
1. bug-report.md
2. enhancement.md
> Add two issue templates

- pkg/globalmanager/incrementallearningjob.go
> gm/incrementallearningjob.go: fix wrong kind

- build/crds/sedna.io_datasets.yaml
- build/crds/sedna.io_incrementallearningjobs.yaml
- build/crds/sedna.io_models.yaml
- build/gm/rbac/gm.yaml
- pkg/apis/sedna/v1alpha1/dataset_types.go
- pkg/apis/sedna/v1alpha1/incrementallearningjob_types.go
- pkg/apis/sedna/v1alpha1/model_types.go
- pkg/globalmanager/common.go
- pkg/globalmanager/downstream.go
- pkg/globalmanager/federatedlearningjob.go
- pkg/globalmanager/incrementallearningjob.go
- pkg/globalmanager/jointinferenceservice.go
- pkg/globalmanager/messagelayer/context.go
- pkg/globalmanager/messagelayer/model/model.go
- pkg/globalmanager/secret_injector.go
- pkg/globalmanager/storage_initializer_injector.go
- pkg/globalmanager/types.go
- pkg/globalmanager/worker.go
- scripts/storage-initializer/Dockerfile
- scripts/storage-initializer/README.md
- scripts/storage-initializer/build_image.sh
- scripts/storage-initializer/download.py
- scripts/storage-initializer/requirements.txt
supported protocols:
1. http(s)
2. s3 compatible with the env ACCESS_KEY_ID, SECRET_ACCESS_KEY,
S3_ENDPOINT_URL
Since the image kfserving/storage-initializer is big(~341MB) and have
some limits with http server, based its code I code the end image size to 54.7MB:
1. support to download more than one uri
2. smaller image size: use minio-client instead of boto3(less than
40MB), remove gcs/azure
3. remove the http-server content-type limits
4. add obs protocol
5. also extract .tar.gz/.zip for s3
6. fix pep8 style
> Add storage-initializer code/Dockerfile

- README.md
- README_zh.md
According to issue: https://github.com/kubeedge/sedna/issues/73, I unified the icon style.  :)
> unified icon style

- README.md
- README_zh.md
- build/kb/Dockerfile
- lib/sedna/core/lifelong_learning/lifelong_learning.py
1. add KB dockerfile
2. add the lifelong learning example link into README.md
3. fix lib lifelong learning bug
> Fix lifelong learning bugs

- build/kb/Dockerfile
> Optimize KB dockerfile

- .github/ISSUE_TEMPLATE/cleanup.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/question.md
1. question
2. documentation
3. cleanup
> Add more github issue templates

- docs/setup/local-up.md
> Add local up install doc

- pkg/globalmanager/federatedlearningjob.go
- pkg/globalmanager/incrementallearningjob.go
- pkg/globalmanager/jointinferenceservice.go
- pkg/globalmanager/lifelonglearningjob.go
- pkg/globalmanager/storage_initializer_injector.go
> GM: modified worker mount mode

- scripts/installation/install.sh
rename the variable LC_BIND_PORT to SENDA_LC_BIND_PORT.
> install.sh: fix LC_BIND_PORT bug

- pkg/localcontroller/manager/dataset.go
fix https://github.com/kubeedge/sedna/issues/136
> LC: send dataset update to GM only when changed

- lib/sedna/algorithms/multi_task_learning/multi_task_learning.py
- lib/sedna/backend/base.py
- lib/sedna/core/lifelong_learning/lifelong_learning.py
1. fix sklearn backend: support args in train/eval/infer
2. fix lifelong constant
> [Lifelong example]: fix the problem from backend and constant

- docs/setup/install.md
1. add GM/LC links
2. add GM/LC deploy form description
> docs: update install guide

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- README_zh.md
- docs/contributing/control-plane/add-a-new-synergy-feature.md
- docs/contributing/control-plane/debug-gm.md
- docs/contributing/control-plane/debug-lc.md
- docs/contributing/control-plane/development.md
- docs/contributing/getting-started.md
- docs/contributing/prepare-environment.md
> Add contributing docs

- examples/incremental_learning/helmet_detection/training/inference.py
- lib/sedna/backend/base.py
- lib/sedna/core/base.py
> [Lib Support] hot model update

- examples/federated_learning/surface_defect_detection/aggregation_worker/aggregate.py
- lib/sedna/service/server/aggregation.py
> fix env variable error in aggregation

- pkg/globalmanager/runtime/storage_initializer_injector.go
> GM: fix the bug of injecting hostpath mount

- scripts/installation/install.sh
1. Add some usage doc comment.
2. Install Sedna latest release version when unspecified.
Signed-off-by: llhuii <liulinghui@huawei.com>
> Optimize installation script

- pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
need to chenge TrainTriggerStatus to EvalTriggerStatus
> Fix IL bug: TrainTriggerStatus used in eval task

- pkg/globalmanager/controllers/incrementallearning/downstream.go
- pkg/localcontroller/gmclient/types.go
- pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
> IL: decouple eval task and deploy task

- scripts/installation/all-in-one.sh
- scripts/installation/install.sh
Allow user passing SEDNA_VERSION without `v` like `0.4.1`
> installation: allow *_VERSION passing without `v`

- scripts/installation/all-in-one.sh
Signed-off-by: llhuii <liulinghui@huawei.com>
> all-in-one: add edgemesh installation

- pkg/globalmanager/config/config.go
- pkg/globalmanager/controllers/manager.go
Signed-off-by: sunhaizhou <sunhaizhou@kingsoft.com>
> make min resync period configurable

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: sunhaizhou <sunhaizhou@kingsoft.com>
> add pr template.

- build/helm/sedna/.helmignore
- build/helm/sedna/Chart.yaml
- build/helm/sedna/README.md
- build/helm/sedna/charts/gm/Chart.yaml
- build/helm/sedna/charts/gm/templates/configmap.yaml
- build/helm/sedna/charts/gm/templates/deployment.yaml
- build/helm/sedna/charts/gm/templates/service.yaml
- build/helm/sedna/charts/gm/values.yaml
- build/helm/sedna/charts/kb/.helmignore
- build/helm/sedna/charts/kb/Chart.yaml
- build/helm/sedna/charts/kb/templates/deployment.yaml
- build/helm/sedna/charts/kb/templates/service.yaml
- build/helm/sedna/charts/kb/values.yaml
- build/helm/sedna/charts/lc/Chart.yaml
- build/helm/sedna/charts/lc/templates/daemonset.yaml
- build/helm/sedna/charts/lc/values.yaml
- build/helm/sedna/crds/sedna.io_datasets.yaml
- build/helm/sedna/crds/sedna.io_federatedlearningjobs.yaml
- build/helm/sedna/crds/sedna.io_incrementallearningjobs.yaml
- build/helm/sedna/crds/sedna.io_jointinferenceservices.yaml
- build/helm/sedna/crds/sedna.io_lifelonglearningjobs.yaml
- build/helm/sedna/crds/sedna.io_models.yaml
- build/helm/sedna/crds/sedna.io_objectsearchservices.yaml
- build/helm/sedna/crds/sedna.io_objecttrackingservices.yaml
- build/helm/sedna/templates/NOTES.txt
- build/helm/sedna/templates/rbac.yaml
- build/helm/sedna/values.yaml
/kind feature
Let sedna support using helm package to install.
Fixes #285 
---
`sedna/build/helm/sedna` is a standard helm directory:
```
build/helm/sedna/
|-- Chart.yaml
|-- README.md
|-- charts
|   |-- gm
|   |   |-- Chart.yaml
|   |   |-- templates
|   |   |   |-- configmap.yaml
|   |   |   |-- deployment.yaml
|   |   |   `-- service.yaml
|   |   `-- values.yaml
|   |-- kb
|   |   |-- Chart.yaml
|   |   |-- templates
|   |   |   |-- deployment.yaml
|   |   |   `-- service.yaml
|   |   `-- values.yaml
|   `-- lc
|       |-- Chart.yaml
|       |-- templates
|       |   `-- daemonset.yaml
|       `-- values.yaml
|-- crds
|   |-- sedna.io_datasets.yaml
|   |-- …
```
> Add sedna installation helm charts

- lib/sedna/core/base.py
Signed-off-by: Vittorio Cozzolino <vittorio.cozzolino@huawei.com>
/kind bug
Fix the regression bug mentioned in #324 .
Fixes #324
> Fix regression bug in JobBase class.

- hack/run-e2e.sh
> Update e2e test script

- lib/sedna/datasources/__init__.py
Signed-off-by: York You <573861119@qq.com>
Support for https://github.com/kubeedge/ianvs/pull/36
https://github.com/kubeedge/sedna/issues/309
> Add JSON data parse

- docs/index/quickstart.md
Signed-off-by: Ryan <zhaoran11@huawei.com>
/kind documentation
Fixes #393
> wrong url in document

- README.md
Signed-off-by: Ryan <zhaoran11@huawei.com>
/kind documentation
the old path is deprecated
Fixes #
> update the path of installation document in README.md

- lib/sedna/backend/__init__.py
Signed-off-by: Lj1ang <2872509481@qq.com>
/kind bug
backend_type is missing here https://github.com/kubeedge/sedna/blob/main/lib/sedna/backend/__init__.py#L23
perhaps I delete it accidently in https://github.com/kubeedge/sedna/pull/376
add backend_type
Fixes #
> two missing line in mindspore backend

- README.md
- README_zh.md
- docs/index/quickstart.md
/kind cleanup
Update slack invitation link to CNCF, ref: https://github.com/kubeedge/community/issues/185
Fixes #
> fix slack url

- pkg/globalmanager/controllers/federatedlearning/federatedlearningjob.go
/kind bug
fix FederatedLearningJob delete error
Fixes #466
> fix FederatedLearningJob delete error

- .github/workflows/main.yaml
/kind bug
The official GitHub has deprecated the Workflow Action v2. Therefore, we need to update its version to v3 or v4. Otherwise, all the pipelines will not be able to pass.
Fixes #
> update workfow actions from v2 to v4
